Update ManagementBasePage.cs
Exception is thrown when manually enqueueing a job from a .NET Core project. I think dat just setting the status code before writing the response might fix it.

System.InvalidOperationException: 'StatusCode cannot be set because the response has already started.'